# Generated by Django 5.0.7 on 2024-07-29 19:08

import datetime
import todos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='creation_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('D', 'Draft'), ('P', 'Pending'), ('C', 'Completed'), ('E', 'Expired')], default='D', max_length=1, validators=[todos.models.validate_todo_status]),
        ),
    ]
