# Generated by Django 5.0.7 on 2024-07-29 17:51

import logs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_time', models.DateTimeField()),
                ('message', models.TextField()),
                ('level', models.CharField(choices=[('I', 'Information'), ('W', 'Warning'), ('E', 'Error'), ('C', 'Critical')], max_length=1, validators=[logs.models.validate_log_level])),
            ],
        ),
    ]
